# Generated by Django 4.1.7 on 2023-04-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='asdcfgbh', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
